##
GET http://localhost:3000/api/v1/mugs

### GET one specific mug ###
GET http://localhost:3000/api/v1/mugs/:id 

###
POST http://localhost:3000/api/v1/mugs HTTP/1.1
content-type: application/json

{
  "title": "Brown Mug",
  "description": "A beautiful brown ceramic mug",
  "price": 15,
  "image": "https://example.com/brown-mug.jpg"
}

###
GET http://localhost:3000/api/v1/carts HTTP/1.1

###
POST http://localhost:3000/api/v1/carts HTTP/1.1

###
POST http://localhost:3000/api/v1/cart-items HTTP/1.1
content-type: application/json

{
  "quantity": 2,
  "cartId": 1,
  "mugId": 3
}